server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: protected-route
          uri: http://dummy-service:8081  # Forward to dummy service
          predicates:
            - Path=/api/data             # Match this URL
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} # Strip /api prefix
            - name: AuthFilter     # Apply our Security Filter