server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: protected-route
          uri: http://dummy-service:8081
          predicates:
            - Path=/api/data
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - name: AuthFilter